language: go

go:
    - 1.5
    - tip

before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get golang.org/x/tools/cmd/vet
    - go get golang.org/x/tools/cmd/goimports
    - go get golang.org/x/lint/golint
    - go get github.com/mattn/goveralls

script:
    - go vet ./...
#    - $HOME/gopath/bin/goveralls -coverprofile=coverage.cov -service=travis-ci
#    - bash <(curl -s https://codecov.io/bash)
    - go test -bench=. -benchmem ./...
    #- sh ./install_all_cmd.sh
